### ISSUE TITLE
Is `curls.website` meant to be registered?

### ISSUE THREAD

**Issue by jonchurch** [madprops/curls#1]
The readme uses `curls.website` for many examples, but this domain has yet to be registered.

Notably, it links to `curls.website/dashboard` as a example of a dashboard implementation the author has created.

> I have my own implementation of a program that uses curls.
>
> It is located at https://curls.website/dashboard.

This goes nowhere, but `curls.merkoba.com/dashboard` does indeed have a dashboard implementation.

The docs related examples make sense to point to an example domain, but the dashboard one is what made me think this was an accident not intentional.

I'll open a PR to update the readme with the assumption it was an accident. 

Close em if not.

**Comment by madprops** [comment]
I used that at first as a placeholder since there was no website. The actual website is https://curls.website/dashboard - I'll edit it to avoid confusion.

**Comment by madprops** [comment]
Alright thanks
